title: Md. Hasnat Shoheb
description: Software Engineer, QA @ Brain Craft Ltd.
baseurl: "/Shoheb/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "hasnat.shoheb@gmail.com"
linkedin: "https://www.linkedin.com/in/md-hasnat-shoheb-611438b9/"
github: "https://github.com/Tahanima"
website: "http://tahanima.github.io/"
medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
